### ISSUE TITLE
My resourcepack isn't working.

### ISSUE THREAD

**Issue by qoinex-dev** [diacritics-owo/icon#2]
Here is a video of all of the files in my resource pack. Please tell me why it doesn't work. The default icons pack works fine.

https://github.com/user-attachments/assets/ac4f6ea3-30d4-4cf1-8bf1-3c24be83750a

**Comment by qoinex-dev** [comment]
Here is the pack [NitroFeather Icon.zip](https://github.com/user-attachments/files/18253080/NitroFeather.Icon.zip)

**Comment by diacritics-owo** [comment]
So sorry for the issue! There was an error in the example resource pack structure. I've updated the description, and your resource pack works when structured as such:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/f713c07f-7260-4976-b02a-60217c67769a" />

**Comment by qoinex-dev** [comment]
Thank you so much for the amazing support! 🙏
